node("ansible_docker"){
    stage("Git checkout"){
        git credentialsId: 'd9f89112-b158-45ac-a5e2-9a1041445308', url: 'https://github.com/DmKazanskiy/example-playbook.git'
    }
    stage("Check ssh key"){
        secret_check=true
    }
    stage("Run playbook"){
        if (secret_check){
            sh 'ansible-galaxy install -r requirements.yml'
            sh 'ansible-playbook site.yml -i inventory/prod.yml'
        }
        else{
            echo 'no more keys'
        }
        
    }
}